Bump build-push-action version
ScilifelabDataCentre/reference-files pull request #5
Opened 2023-03-27 09:14 UTC by eriksjolund

* bump version to docker/build-push-action@v4

* fix typo

2023-03-27 19:45 UTC, talavis requested changes
The multi arch build is in docker-multiarch.yml

2023-03-29 08:24 UTC, eriksjolund commented
Thanks for the review. I reworked the PR to only bump the build-push-action version and to fix a typo.

2023-03-29 08:27 UTC, talavis commented on README.md
> +* Build and publish Docker images (`docker.yml`). (Optional: Adjust the `platforms` attribute to build images for additional architectures like linux/arm64`)
I think you forgot to remove this one.

2023-03-29 08:36 UTC, eriksjolund commented on README.md
> +* Build and publish Docker images (`docker.yml`). (Optional: Adjust the `platforms` attribute to build images for additional architectures like linux/arm64`)
You're right. Now fixed.

2023-03-29 08:40 UTC, talavis approved these changes

2023-03-29 10:29 UTC, merged